git clone --depth 1 https://github.com/notofonts/latin-greek-cyrillic
git clone --depth 1 https://github.com/notofonts/bengali
git clone --depth 1 https://github.com/notofonts/brahmi
git clone --depth 1 https://github.com/notofonts/chakma
git clone --depth 1 https://github.com/notofonts/devanagari
git clone --depth 1 https://github.com/notofonts/grantha
git clone --depth 1 https://github.com/notofonts/gujarati
git clone --depth 1 https://github.com/notofonts/gunjala-gondi
git clone --depth 1 https://github.com/notofonts/gurmukhi
git clone --depth 1 https://github.com/notofonts/kaithi
git clone --depth 1 https://github.com/notofonts/kannada
git clone --depth 1 https://github.com/notofonts/kharoshthi
git clone --depth 1 https://github.com/notofonts/khojki
git clone --depth 1 https://github.com/notofonts/khudawadi
git clone --depth 1 https://github.com/notofonts/lepcha
git clone --depth 1 https://github.com/notofonts/limbu
git clone --depth 1 https://github.com/notofonts/mahajani
git clone --depth 1 https://github.com/notofonts/malayalam
git clone --depth 1 https://github.com/notofonts/masaram-gondi
git clone --depth 1 https://github.com/notofonts/meetei-mayek
git clone --depth 1 https://github.com/notofonts/modi
git clone --depth 1 https://github.com/notofonts/mro
git clone --depth 1 https://github.com/notofonts/multani
git clone --depth 1 https://github.com/notofonts/nag-mundari
git clone --depth 1 https://github.com/notofonts/nandinagari
git clone --depth 1 https://github.com/notofonts/newa
git clone --depth 1 https://github.com/notofonts/ol-chiki
git clone --depth 1 https://github.com/notofonts/oriya
git clone --depth 1 https://github.com/notofonts/saurashtra
git clone --depth 1 https://github.com/notofonts/sharada
git clone --depth 1 https://github.com/notofonts/siddham
git clone --depth 1 https://github.com/notofonts/sinhala
git clone --depth 1 https://github.com/notofonts/syloti-nagri
git clone --depth 1 https://github.com/notofonts/tamil
git clone --depth 1 https://github.com/notofonts/tangsa
git clone --depth 1 https://github.com/notofonts/telugu
git clone --depth 1 https://github.com/notofonts/tirhuta

md fonts