gftools builder latin-greek-cyrillic\sources\config-sans.yaml --no-autohint        & xcopy latin-greek-cyrillic\fonts fonts /S /Y
gftools builder bengali\sources\config-sans-bengali.yaml --no-autohint             & xcopy bengali\fonts fonts /S /Y
gftools builder brahmi\sources\config-sans-brahmi.yaml --no-autohint               & xcopy brahmi\fonts fonts /S /Y
gftools builder chakma\sources\config-sans-chakma.yaml --no-autohint               & xcopy chakma\fonts fonts /S /Y
gftools builder devanagari\sources\config-sans-devanagari.yaml --no-autohint       & xcopy devanagari\fonts fonts /S /Y
gftools builder grantha\sources\config-sans-grantha.yaml --no-autohint             & xcopy grantha\fonts fonts /S /Y
gftools builder gujarati\sources\config-sans-gujarati.yaml --no-autohint           & xcopy gujarati\fonts fonts /S /Y
gftools builder gunjala-gondi\sources\config-sans-gunjala-gondi.yaml --no-autohint & xcopy gunjala-gondi\fonts fonts /S /Y
gftools builder gurmukhi\sources\config-sans-gurmukhi.yaml --no-autohint           & xcopy gurmukhi\fonts fonts /S /Y
gftools builder kaithi\sources\config-sans-kaithi.yaml --no-autohint               & xcopy kaithi\fonts fonts /S /Y
gftools builder kannada\sources\config-sans-kannada.yaml --no-autohint             & xcopy kannada\fonts fonts /S /Y
gftools builder kharoshthi\sources\config-sans-kharoshthi.yaml --no-autohint       & xcopy kharoshthi\fonts fonts /S /Y
gftools builder khojki\sources\config-sans-khojki.yaml --no-autohint               & xcopy khojki\fonts fonts /S /Y
gftools builder khudawadi\sources\config-sans-khudawadi.yaml --no-autohint         & xcopy khudawadi\fonts fonts /S /Y
gftools builder lepcha\sources\config-sans-lepcha.yaml --no-autohint               & xcopy lepcha\fonts fonts /S /Y
gftools builder limbu\sources\config-sans-limbu.yaml --no-autohint                 & xcopy limbu\fonts fonts /S /Y
gftools builder mahajani\sources\config-sans-mahajani.yaml --no-autohint           & xcopy mahajani\fonts fonts /S /Y
gftools builder malayalam\sources\config-sans-malayalam.yaml --no-autohint         & xcopy malayalam\fonts fonts /S /Y
gftools builder masaram-gondi\sources\config-sans-masaram-gondi.yaml --no-autohint & xcopy masaram-gondi\fonts fonts /S /Y
gftools builder meetei-mayek\sources\config-sans-meetei-mayek.yaml --no-autohint   & xcopy meetei-mayek\fonts fonts /S /Y
gftools builder modi\sources\config-sans-modi.yaml --no-autohint                   & xcopy modi\fonts fonts /S /Y
gftools builder mro\sources\config-sans-mro.yaml --no-autohint                     & xcopy mro\fonts fonts /S /Y
gftools builder multani\sources\config-sans-multani.yaml --no-autohint             & xcopy multani\fonts fonts /S /Y
gftools builder nag-mundari\sources\config.yaml --no-autohint                      & xcopy nag-mundari\fonts fonts /S /Y
gftools builder nandinagari\sources\config-sans-nandinagari.yaml --no-autohint     & xcopy nandinagari\fonts fonts /S /Y
gftools builder newa\sources\config-sans-newa.yaml --no-autohint                   & xcopy newa\fonts fonts /S /Y
gftools builder ol-chiki\sources\config-sans-ol-chiki.yaml --no-autohint           & xcopy ol-chiki\fonts fonts /S /Y
gftools builder oriya\sources\config-sans-oriya.yaml --no-autohint                 & xcopy oriya\fonts fonts /S /Y
gftools builder saurashtra\sources\config-sans-saurashtra.yaml --no-autohint       & xcopy saurashtra\fonts fonts /S /Y
gftools builder sharada\sources\config-sans-sharada.yaml --no-autohint             & xcopy sharada\fonts fonts /S /Y
gftools builder siddham\sources\config-sans-siddham.yaml --no-autohint             & xcopy siddham\fonts fonts /S /Y
gftools builder sinhala\sources\config-sans-sinhala.yaml --no-autohint             & xcopy sinhala\fonts fonts /S /Y
gftools builder syloti-nagri\sources\config-sans-syloti-nagri.yaml --no-autohint   & xcopy syloti-nagri\fonts fonts /S /Y
gftools builder tamil\sources\config-sans-tamil.yaml --no-autohint                 & xcopy tamil\fonts fonts /S /Y
gftools builder tamil\sources\config-sans-tamil-supplement.yaml --no-autohint      & xcopy tamil\fonts fonts /S /Y
gftools builder tangsa\sources\config-sans-tangsa.yaml --no-autohint               & xcopy tangsa\fonts fonts /S /Y
gftools builder telugu\sources\config-sans-telugu.yaml --no-autohint               & xcopy telugu\fonts fonts /S /Y
gftools builder tirhuta\sources\config-sans-tirhuta.yaml --no-autohint             & xcopy tirhuta\fonts fonts /S /Y

gftools builder latin-greek-cyrillic\sources\config-serif.yaml --no-autohint   & xcopy latin-greek-cyrillic\fonts fonts /S /Y
gftools builder bengali\sources\config-serif-bengali.yaml --no-autohint        & xcopy bengali\fonts fonts /S /Y
gftools builder devanagari\sources\config-serif-devanagari.yaml --no-autohint  & xcopy devanagari\fonts fonts /S /Y
gftools builder grantha\sources\config-serif-grantha.yaml --no-autohint        & xcopy grantha\fonts fonts /S /Y
gftools builder gujarati\sources\config-serif-gujarati.yaml --no-autohint      & xcopy gujarati\fonts fonts /S /Y
gftools builder gurmukhi\sources\config-serif-gurmukhi.yaml --no-autohint      & xcopy gurmukhi\fonts fonts /S /Y
gftools builder kannada\sources\config-serif-kannada.yaml --no-autohint        & xcopy kannada\fonts fonts /S /Y
gftools builder khojki\sources\config-serif-khojki.yaml --no-autohint          & xcopy khojki\fonts fonts /S /Y
gftools builder malayalam\sources\config-serif-malayalam.yaml --no-autohint    & xcopy malayalam\fonts fonts /S /Y
gftools builder oriya\sources\config-serif-oriya.yaml --no-autohint            & xcopy oriya\fonts fonts /S /Y
gftools builder sinhala\sources\config-serif-sinhala.yaml --no-autohint        & xcopy sinhala\fonts fonts /S /Y
gftools builder tamil\sources\config-serif-tamil.yaml --no-autohint            & xcopy tamil\fonts fonts /S /Y
gftools builder telugu\sources\config-serif-telugu.yaml --no-autohint          & xcopy telugu\fonts fonts /S /Y