yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" latin-greek-cyrillic\sources\config-sans.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" bengali\sources\config-sans-bengali.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" brahmi\sources\config-sans-brahmi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" chakma\sources\config-sans-chakma.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" devanagari\sources\config-sans-devanagari.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" grantha\sources\config-sans-grantha.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" gujarati\sources\config-sans-gujarati.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" gunjala-gondi\sources\config-sans-gunjala-gondi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" gurmukhi\sources\config-sans-gurmukhi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" kaithi\sources\config-sans-kaithi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" kannada\sources\config-sans-kannada.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" kharoshthi\sources\config-sans-kharoshthi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" khojki\sources\config-sans-khojki.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" khudawadi\sources\config-sans-khudawadi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" lepcha\sources\config-sans-lepcha.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" limbu\sources\config-sans-limbu.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" mahajani\sources\config-sans-mahajani.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" malayalam\sources\config-sans-malayalam.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" masaram-gondi\sources\config-sans-masaram-gondi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" meetei-mayek\sources\config-sans-meetei-mayek.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" modi\sources\config-sans-modi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" mro\sources\config-sans-mro.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" multani\sources\config-sans-multani.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" nag-mundari\sources\config.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" nandinagari\sources\config-sans-nandinagari.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" newa\sources\config-sans-newa.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" ol-chiki\sources\config-sans-ol-chiki.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" oriya\sources\config-sans-oriya.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" saurashtra\sources\config-sans-saurashtra.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" sharada\sources\config-sans-sharada.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" siddham\sources\config-sans-siddham.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" sinhala\sources\config-sans-sinhala.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" syloti-nagri\sources\config-sans-syloti-nagri.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" tamil\sources\config-sans-tamil.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" tamil\sources\config-sans-tamil-supplement.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" tangsa\sources\config-sans-tangsa.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" telugu\sources\config-sans-telugu.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" tirhuta\sources\config-sans-tirhuta.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" latin-greek-cyrillic\sources\config-serif.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" bengali\sources\config-serif-bengali.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" devanagari\sources\config-serif-devanagari.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" grantha\sources\config-serif-grantha.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" gujarati\sources\config-serif-gujarati.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" gurmukhi\sources\config-serif-gurmukhi.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" kannada\sources\config-serif-kannada.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" khojki\sources\config-serif-khojki.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" malayalam\sources\config-serif-malayalam.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" oriya\sources\config-serif-oriya.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" sinhala\sources\config-serif-sinhala.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" tamil\sources\config-serif-tamil.yaml -i
yq "with_entries(select(.key=="""familyName""" or .key=="""sources"""))|(.buildOTF=false)|(.buildVariable=false)" telugu\sources\config-serif-telugu.yaml -i