name: New Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'true' 

      - name: YAML
        uses: mikefarah/yq@master
        with:
          cmd: find -name "config*.yaml" -exec yq 'with_entries(select(.key=="familyName" or .key=="sources"))|(.buildOTF=false)|(.buildVariable=false)|(.buildWebfont=false)|(.buildSmallCap=false)' {} -i \;

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python modules  
        run: pip install fonttools gftools

      - name: Build fonts
        run: |
          gftools builder latin-greek-cyrillic/sources/config-sans.yaml
          gftools builder latin-greek-cyrillic/sources/config-serif.yaml
          find -name "config*.yaml" -not -path "./latin*" -not -name "*-ui.yaml" -exec gftools builder {} \;

      - name: Copy fonts
        run: |
          mkdir fonts
          rsync --recursive latin-greek-cyrillic/fonts/ fonts/
          git submodule foreach 'rsync --recursive fonts/ ../fonts/'
          dir --recursive fonts/
          cd fonts/ttf
          ls -1 NotoSans*-Regular.ttf >sans.txt
          ls -1 NotoSerif*-Regular.ttf >serif.txt

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Merge metadata
        working-directory: ./fonts/ttf
        run: |
          find -name "*-Regular.ttf" -exec ttx -t name {} \;
          dotnet run --project ../../.github/workflows/merge.csproj -- sans.txt ../../sans.ttx "Noto Sans Indic" >> $GITHUB_ENV
          dotnet run --project ../../.github/workflows/merge.csproj -- serif.txt ../../serif.ttx "Noto Serif Indic"
          cp --force release.md ../../
          cat ../../sans.ttx
          cat ../../serif.ttx
          cat ../../release.md

      - name: Merge fonts
        working-directory: ./fonts/ttf
        run: |
          pyftmerge --input-file=sans.txt --output-file=../../NotoSansIndic.ttf --import-file=../../sans.ttx --drop-tables=vhea,vmtx --verbose
          pyftmerge --input-file=serif.txt --output-file=../../NotoSerifIndic.ttf --import-file=../../serif.ttx --drop-tables=vhea,vmtx --verbose
        
      - name: Create release
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Release Action"
          git add *.ttx
          git add release.md
          git commit -m "v$RELEASE_VERSION bump"
          git push
          gh release create v$RELEASE_VERSION --title "Noto Indic v$RELEASE_VERSION" --notes-file release.md NotoSansIndic.ttf NotoSerifIndic.ttf
