name: Update Submodules

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      newCommit: ${{ steps.commit.outputs.newCommit }}

    steps:
      - uses: actions/checkout@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: git submodule update --init --remote --depth 1

      - name: Commit submodules
        id: commit
        continue-on-error: true  
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Update Action"
          git add --all
          git commit -m "update submodules" && git push && echo "newCommit=1" >> "$GITHUB_OUTPUT"

  release:
    if: ${{ needs.update.outputs.newCommit == '1' }}
    needs: update
    uses: ./.github/workflows/release.yaml